//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClima
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SeguridadEntities : DbContext
    {
        public SeguridadEntities()
            : base("name=SeguridadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<RolePermiso> RolePermiso { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<usuarioRole> usuarioRole { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Autentica(string usuario, string password)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Autentica", usuarioParameter, passwordParameter);
        }
    
        public virtual int BorraRolePermiso(Nullable<int> id_role, Nullable<int> id_permiso)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var id_permisoParameter = id_permiso.HasValue ?
                new ObjectParameter("id_permiso", id_permiso) :
                new ObjectParameter("id_permiso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorraRolePermiso", id_roleParameter, id_permisoParameter);
        }
    
        public virtual int BorraRoleUsuario(Nullable<int> id_usuario, Nullable<int> id_role)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorraRoleUsuario", id_usuarioParameter, id_roleParameter);
        }
    
        public virtual ObjectResult<ComplementoPermisosRole_Result> ComplementoPermisosRole(Nullable<int> role)
        {
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComplementoPermisosRole_Result>("ComplementoPermisosRole", roleParameter);
        }
    
        public virtual ObjectResult<ComplementoRolesusuario_Result> ComplementoRolesusuario(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComplementoRolesusuario_Result>("ComplementoRolesusuario", usuarioParameter);
        }
    
        public virtual ObjectResult<DatosUsuario_Result> DatosUsuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosUsuario_Result>("DatosUsuario", usuarioParameter);
        }
    
        public virtual ObjectResult<DatosUsuarioPorId_Result> DatosUsuarioPorId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosUsuarioPorId_Result>("DatosUsuarioPorId", idParameter);
        }
    
        public virtual int InsertaPermiso(string nombre, string descripcion, string elementoRelacionado, string idElemento, ObjectParameter id)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var elementoRelacionadoParameter = elementoRelacionado != null ?
                new ObjectParameter("ElementoRelacionado", elementoRelacionado) :
                new ObjectParameter("ElementoRelacionado", typeof(string));
    
            var idElementoParameter = idElemento != null ?
                new ObjectParameter("idElemento", idElemento) :
                new ObjectParameter("idElemento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaPermiso", nombreParameter, descripcionParameter, elementoRelacionadoParameter, idElementoParameter, id);
        }
    
        public virtual int InsertaRole(string nombre, string descripcion, ObjectParameter id)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaRole", nombreParameter, descripcionParameter, id);
        }
    
        public virtual int InsertaRolePermiso(Nullable<int> id_role, Nullable<int> id_permiso)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var id_permisoParameter = id_permiso.HasValue ?
                new ObjectParameter("id_permiso", id_permiso) :
                new ObjectParameter("id_permiso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaRolePermiso", id_roleParameter, id_permisoParameter);
        }
    
        public virtual int InsertaRoleUsuario(Nullable<int> id_role, Nullable<int> id_usuario)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaRoleUsuario", id_roleParameter, id_usuarioParameter);
        }
    
        public virtual int InsertaUsuario(string usuario, string nombres, string apellidos, string password, ObjectParameter id)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaUsuario", usuarioParameter, nombresParameter, apellidosParameter, passwordParameter, id);
        }
    
        public virtual ObjectResult<PermisosRole_Result> PermisosRole(Nullable<int> role)
        {
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PermisosRole_Result>("PermisosRole", roleParameter);
        }
    
        public virtual ObjectResult<PermisosUsuario_Result> PermisosUsuario(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PermisosUsuario_Result>("PermisosUsuario", usuarioParameter);
        }
    
        public virtual ObjectResult<Rolesusuario_Result> Rolesusuario(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rolesusuario_Result>("Rolesusuario", usuarioParameter);
        }
    
        public virtual ObjectResult<ComplementoPermisosRole1_Result> ComplementoPermisosRole1(Nullable<int> role)
        {
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComplementoPermisosRole1_Result>("ComplementoPermisosRole1", roleParameter);
        }
    
        public virtual ObjectResult<ComplementoRolesusuario1_Result> ComplementoRolesusuario1(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComplementoRolesusuario1_Result>("ComplementoRolesusuario1", usuarioParameter);
        }
    
        public virtual ObjectResult<DatosUsuario1_Result> DatosUsuario1(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosUsuario1_Result>("DatosUsuario1", usuarioParameter);
        }
    
        public virtual ObjectResult<DatosUsuarioPorId1_Result> DatosUsuarioPorId1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosUsuarioPorId1_Result>("DatosUsuarioPorId1", idParameter);
        }
    
        public virtual int InsertaPermiso1(string nombre, string descripcion, string elementoRelacionado, string idElemento, ObjectParameter id)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var elementoRelacionadoParameter = elementoRelacionado != null ?
                new ObjectParameter("ElementoRelacionado", elementoRelacionado) :
                new ObjectParameter("ElementoRelacionado", typeof(string));
    
            var idElementoParameter = idElemento != null ?
                new ObjectParameter("idElemento", idElemento) :
                new ObjectParameter("idElemento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaPermiso1", nombreParameter, descripcionParameter, elementoRelacionadoParameter, idElementoParameter, id);
        }
    
        public virtual int InsertaRole1(string nombre, string descripcion, ObjectParameter id)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaRole1", nombreParameter, descripcionParameter, id);
        }
    
        public virtual int InsertaRolePermiso1(Nullable<int> id_role, Nullable<int> id_permiso)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var id_permisoParameter = id_permiso.HasValue ?
                new ObjectParameter("id_permiso", id_permiso) :
                new ObjectParameter("id_permiso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaRolePermiso1", id_roleParameter, id_permisoParameter);
        }
    
        public virtual int InsertaRoleUsuario1(Nullable<int> id_role, Nullable<int> id_usuario)
        {
            var id_roleParameter = id_role.HasValue ?
                new ObjectParameter("id_role", id_role) :
                new ObjectParameter("id_role", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaRoleUsuario1", id_roleParameter, id_usuarioParameter);
        }
    
        public virtual int InsertaUsuario1(string usuario, string nombres, string apellidos, string password, ObjectParameter id)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaUsuario1", usuarioParameter, nombresParameter, apellidosParameter, passwordParameter, id);
        }
    
        public virtual ObjectResult<PermisosRole1_Result> PermisosRole1(Nullable<int> role)
        {
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PermisosRole1_Result>("PermisosRole1", roleParameter);
        }
    
        public virtual ObjectResult<PermisosUsuario1_Result> PermisosUsuario1(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PermisosUsuario1_Result>("PermisosUsuario1", usuarioParameter);
        }
    
        public virtual ObjectResult<Rolesusuario1_Result> Rolesusuario1(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rolesusuario1_Result>("Rolesusuario1", usuarioParameter);
        }
    }
}
